name: My-GitHub-basics

on:
  push:
    branches: [master]
jobs:
  my_testing:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Hello Message
      run: echo "Hello World my testing deploy"
      
    
        
