# This is a basic workflow to help you get started with Actions

name: Hello-world

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
     - master
 
  workflow_dispatch:

jobs:
  
  Testing:
    
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello World
      run: echo "hello world Testing"
      
  Testing_deploy:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello World
      run: echo "hello world Deploy"
    
