name: CI
on:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:      
      matrix:        
        node-version: [11.x]
      
    steps:      
  # Use the node version specified in the strategy    
    - name: Use Node.js ${{ matrix.node-version }}      
      uses: actions/setup-node@v1      
      with:        
        node-version: ${{ matrix.node-version }}
   
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Install packages
      run: |
        cd react-application-folder/
    - name: Production build      
      run: |        
        unset CI
        yarn build
   yarn install
# name : Upload site
# env:
#   EB_PACKAGE_S3_BUCKET_NAME : "github-bucket-packages"
#   AWS_REGION_NAME           : "eu-north-1"
  
# on:
#   push:
#     branches:
#     - master
    
# jobs:

#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 12
#     - run: npm ci
#     - run: npm run build
#     - name: asdas
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_ID_KEY }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRETs_KEY }}
#         aws-region: ${{ env.AWS_REGION_NAME }}
          
#     - name: Deploy to S3 +
#       run: aws s3 sync . s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }} --delete
